### ISSUE TITLE
Needs to support --exclude and not just --exclude-dir

### ISSUE THREAD

**Issue by brian-mann** [bahmutov/stop-only#20]
Need to exclude a file and not just folder.

**Comment by bahmutov** [comment]
why do we need this?

**Comment by brian-mann** [comment]
Because I need to exclude a file and not a folder. As is I've turned off `stop-only` in the `cypress` repo because it detects that I'm using an only in something I am not. I find it highly inflexible because I want much more targeted globs and not just a folder to look in. A folder contains so much other stuff besides actual `spec` files.

**Comment by bahmutov** [comment]
And what file has “.only” in our projects ? I mean it is simple to add new feature here, just wondering if we are searching entire repo rather than test folder

**Comment by brian-mann** [comment]
You are searching all of `packages` which effectively searches everything. But regardless, I have code in a `spec_helper` that looks like an only but it is not. I only want it targeted to actual spec files, and even then I want to be able to override them. I use `.only` in my e2e tests as well to actually **test** the behavior of `.only`. Without being able to conditionally turn it off, all is lost.

**Comment by bahmutov** [comment]
I see. Ok will add it
